spring.application.name=home_store

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Currently using development credentials, but during production production, we will use production profile which is not pushed to get up. Later instruction will be added in README.md

# DataSource Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/home_store_db
spring.datasource.username=home_store_user
spring.datasource.password=home_store
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true