server:
  port: 8086 # Changed from 8085 to avoid conflict with inventory-service
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres:5432/homestore_order_db
    username: homestore_user
    password: user_homestore
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
