spring:
  application:
    name: product-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: "configserver:"

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
