spring:
  application:
    name: product-service
  profiles:
    active: dev
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  config:
    import: "optional:configserver:"
#  autoconfigure:
#    exclude:
#      - com.google.cloud.spring.autoconfigure.storage.GcpStorageAutoConfiguration
#      - com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration

# Firebase Configuration
firebase:
  enabled: true  # Set to true to enable Firebase Storage
  storage:
    bucket: homestore-c8279.firebasestorage.app
  credentials:
    location: serviceAccountKey.json

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
