server:
  port: 8085 # Or any other available port

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://homestore-db:5432/homestore_inventory_db # Ensure this DB is created
    username: admin
    password: password # Consider using environment variables or Spring Cloud Config for secrets
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Or 'validate' in production after initial schema setup
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      enabled: false
    web:
      server:
        request:
          autotime:
            enabled: false
    binders:
      processor:
        enabled: false
      system:
        enabled: false
      jvm:
        enabled: false
