spring:
  application:
    name: store-service
  profiles:
    active: dev
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  config:
    import: "configserver:"

server:
  port: 8083


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
